### ISSUE TITLE
FPP Error

### ISSUE THREAD

**Issue by cgeckeler** [michaelbekos/crossingresolution#121]
e.g. new random graph with 10 nodes and 10 edges (connected, no stray nodes)
Run FPP => java.lang.ClassCastException: com.yworks.yfiles.algorithms.Dart cannot be cast to com.yworks.yfiles.algorithms.GraphObject

**Comment by Amssen** [comment]
The error commes from graphs which are not biconnected. Now there is a check for this, before it run the fpp.
