### ISSUE TITLE
Possible Bug: Chain Stack Resetting

### ISSUE THREAD

**Issue by cgeckeler** [michaelbekos/crossingresolution#122]
Depending on how the chains are implemented, the vertexstack should be declared in the MainFrame so they can be reset when loading new graph, reloading, etc.

**Comment by Hackbrett3X** [comment]
The VertexStack class is no longer used. But the same might apply to the new RemovedNodes and RemovedChains classes.

**Comment by cgeckeler** [comment]
Probably, when the graph changes (new graph loaded, etc) all the stacks should be reset/cleared. Currently on the master its still a bug, but with all the changes and the chains also being implemented its worth keeping in mind.
