### ISSUE TITLE
Random Movement: Decreasing Angle Bug when Stopping

### ISSUE THREAD

**Issue by cgeckeler** [michaelbekos/crossingresolution#138]
Stopping the algorithm sometimes results in movement that decreases the best minimum angle, easiest to see with new layered grid graph (90 deg). Starting and stopping several times, at some point after pressing stop a node will move, resulting in < 90.

**Comment by Hackbrett3X** [comment]
I tried about 100 times and could not reproduce it... could you check if its still there? I made some modifications to the executor earlier.

**Comment by cgeckeler** [comment]
It appears to no longer be present on the current master branch.
