### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by plneappl** [michaelbekos/crossingresolution#14]
- [x] Cleanup MainFrame.java
- [x] Klassenstruktur verbessern
- [x] Orderstruktur verbessern
- [x] Restore Menu Functions SpringEmbedder, Layouter
- [x] Cleanup project
- [x] Comment Code

**Comment by jewolz** [comment]
Habe viel schon kommentiert, Simon bitte kommentiere noch bei dir bissle Zeug, wo code nicht eindeutig. Cleanup der unnötigen Klassen durchgeführt
