### ISSUE TITLE
Chains: NPE

### ISSUE THREAD

**Issue by cgeckeler** [michaelbekos/crossingresolution#140]
Nullpointer when removing chains, as well as when no more chains are left (and pressing button)

**Comment by cgeckeler** [comment]
Also NPE when not using a loaded graph (ie new random graph)

**Comment by Hackbrett3X** [comment]
The implementation depends on a non-null tag of the nodes in order to uniquely identify them. We might add random tags if they are null. Or we could adapat the random graph generators to add tags.
