### ISSUE TITLE
Competition Environment

### ISSUE THREAD

**Issue by Glorring** [michaelbekos/crossingresolution#170]
So I would reduce it to the max and focus on the following.

- [ ]  Random Movement
- [ ]  Clinch Nodes
- [ ] Gridding
- [ ] Only work on Crossing Resolution

**Comment by cgeckeler** [comment]
Additionally from 11.07.18:
- [ ]  Only User Mode as a checkbox at the bottom (manual always on)
- [ ]  File Menu: only JSON open/save/save as
- [ ]  No GraphOps shortcuts
- [ ]  Add FPP, organix, jitter from Misc. as buttons

**Comment by cgeckeler** [comment]
fix bugs

**Comment by cgeckeler** [comment]
fixed, see 4a491cf8908983c30d3bd8fcd36adee67bb93bde
