### ISSUE TITLE
Refactor layout executor

### ISSUE THREAD

**Issue by Hackbrett3X** [michaelbekos/crossingresolution#61]
All algorithms should be run by a common executor class. Find similarities of the algorithms. This should probably result in a merge of the current ForceAlgorithmApplier and IGraphLayoutExecutor classes.

Also consider:
 - sidebar customization
 - start/stop/pause buttons
 - automatic storing of the best result

**Comment by Hackbrett3X** [comment]
I think most of the code that is now in ClinchLayoutExecutor could be moved to GenericLayoutExecutor:
 - duplicate IGraph field
 - ILayout field
 - updateViewAlgo, initializeAlgorithm, updateStepAlgorithm, finishAlgorithm

My original idea was that the other algorithms should implement ILayout. Then there's no need for separate executors for each algorithm (except for the initialization).

**Comment by cgeckeler** [comment]
Thanks for your feedback, those are good points. The problem I found was that the ForceAlgorithmApplier is quite a large and widespread class, used for several different algorithms (eg. the main force algo and spring embedder) and reducing that to fit say the ILayout would be quite difficult. Currently each algorithm implements an executor, but that is essentially only the constructor, and the algo specific  initializeAlgorithm, updateStepAlgorithm, finishAlgorithm, and nothing else is needed (might be more presentable as an interface like ILayout or then GenericLayoutExecutor).

**Comment by Hackbrett3X** [comment]
That's true. Maybe we should start by refactoring the FAA. We probably should split it into several classes and move some code to the actual algorithms or utility classes. I definitely don't like the kitchen-sink style of this class...

If I find the time I can do try that myself.
