### ISSUE TITLE
Random Movement Enhancements

### ISSUE THREAD

**Issue by cgeckeler** [michaelbekos/crossingresolution#77]
Bias/weight for nodes connected to minimal angle crossing:
e.g. different probability distributions depending on graph:
-small graph: uniform distribution
-large graphs: nodes around crossing have higher probability of being chosen
-when reinserting chains (deg. 2 vertices), these have higher probability also

**Comment by Hackbrett3X** [comment]
"-when reinserting chains (deg. 2 vertices), these have higher probability also" seems to be quite complicated to implement...
